protocol_semantic_version = 133143986176
genesis_root = "0x1aaffff6f5dc5e564df293840da45c37c007020d1b79123e6564087b7e19b906"
genesis_rollup_leaf_index = 104
genesis_batch_commitment = "0x1d4158f0a492a50c64664186e11b85c21685d6311ff7dd0f9a9aca2600d6643e"
bootloader_hash = "0x0100098b957008dda66d37766dc973bac46b3b69405d9cd584aa64548a17f43f"
default_aa_hash = "0x010005f77c5bcc9dfe0869ea74a11c79eee954e100d1f79c3fe19f98307b3689"
evm_emulator_hash = "0x01000d8bae37b82f311186426184866498b357f41d7a02ced11f3e3fbfbacd63"

[prover]
recursion_scheduler_level_vk_hash = "0x1ffc56111a5cfaf5db387f6a31408ad20217e9bc1f31f2f5c1bd38b0d6d7968b"
fflonk_snark_wrapper_vk_hash = "0x49eae0bf5c7ea580f4979b366e52b386adc5f42e2ce50fc1d3c4de9a86052bff"
