protocol_semantic_version = 133143986176
genesis_root = "0xfeea33ca9ea640919161c06dd59a68b85d47cbffa2ea70355d76b688e563b8ad"
genesis_rollup_leaf_index = 104
genesis_batch_commitment = "0x3b177a562e7ea611b2d35ec245ce63f0eefb92dbf76cfd1494a7630e2c0a25fc"
bootloader_hash = "0x0100098b957008dda66d37766dc973bac46b3b69405d9cd584aa64548a17f43f"
default_aa_hash = "0x010005f7e0ee5bb66e1e59d296f47360e0f2a7d33d2ea5c8f77c0d6c6759c930"
evm_emulator_hash = "0x01000d8bae37b82f311186426184866498b357f41d7a02ced11f3e3fbfbacd63"
