protocol_semantic_version = 133143986176
genesis_root = "0x0f6afea3036bafdaef5b7bae9b05501701220d8ce8753b4ad0816c57d3cd4ed2"
genesis_rollup_leaf_index = 104
genesis_batch_commitment = "0xb95c6724cb1c04cd46cd36527a28bec786fb8d8cf583266e2c07c88e1d6088d9"
bootloader_hash = "0x0100098b957008dda66d37766dc973bac46b3b69405d9cd584aa64548a17f43f"
default_aa_hash = "0x010005f7622adb24d6b96ff0a770f5d3ed4847c21fbea82ed7bd4e6f8ecd16c6"
evm_emulator_hash = "0x01000d8bae37b82f311186426184866498b357f41d7a02ced11f3e3fbfbacd63"

[prover]
recursion_scheduler_level_vk_hash = "0x1ffc56111a5cfaf5db387f6a31408ad20217e9bc1f31f2f5c1bd38b0d6d7968b"
fflonk_snark_wrapper_vk_hash = "0x49eae0bf5c7ea580f4979b366e52b386adc5f42e2ce50fc1d3c4de9a86052bff"
