protocol_semantic_version = 120259084288
genesis_root = "0xfceb844c56a91f24f22254080ba7a4dc7b79a94b526614ffb36ac84c6bf4cc56"
genesis_rollup_leaf_index = 104
genesis_batch_commitment = "0x4483c4ecbce5716bb274291217a8be1d976ab4c8212035dc116230a7aa117233"
bootloader_hash = "0x0100098b957008dda66d37766dc973bac46b3b69405d9cd584aa64548a17f43f"
default_aa_hash = "0x010005f7c25084132c5cc18e19c4b8df3ae3cb37a24d9dbd8aaa042cfcbe6f5f"
evm_emulator_hash = "0x01000d8bae37b82f311186426184866498b357f41d7a02ced11f3e3fbfbacd63"
