protocol_semantic_version = 133143986176
genesis_root = "0xaa7eaa4388da7ec71007aeac9c7af0fbde8ed0621b8f64c43894737f7a0b4ace"
genesis_rollup_leaf_index = 104
genesis_batch_commitment = "0xa0bd84414e8cf8bb024e4b67727a4194577fe964f7ab2dda7dd0e161510e5279"
bootloader_hash = "0x0100098b957008dda66d37766dc973bac46b3b69405d9cd584aa64548a17f43f"
default_aa_hash = "0x010005f7833a9c9d0e4e64b1aae6fda44c58dcd5356ad353a480c106e73b767e"
evm_emulator_hash = "0x01000d8bae37b82f311186426184866498b357f41d7a02ced11f3e3fbfbacd63"
