protocol_semantic_version = 133143986176
genesis_root = "0xf306e4115c7cba7dbc00ffb35e1b210579fd0c05054804e2dd901048d8e71e08"
genesis_rollup_leaf_index = 104
genesis_batch_commitment = "0x48f9fb337637dd6ae6c978efcee14ee96baf8e147e11db3253b8f945291eac81"
bootloader_hash = "0x0100098b957008dda66d37766dc973bac46b3b69405d9cd584aa64548a17f43f"
default_aa_hash = "0x010005f7833a9c9d0e4e64b1aae6fda44c58dcd5356ad353a480c106e73b767e"
evm_emulator_hash = "0x01000d8bae37b82f311186426184866498b357f41d7a02ced11f3e3fbfbacd63"
