era_chain_id = 324
testnet_verifier = false
v26_verifier = 0xdb3300726556AFA413A11aF474a8cFDa4D7fc5a5
v26_diamond_init = 0x6eFEF84404fB3d02DD5596Bc5824eF8a71689093
v26_l1_asset_router = 0x8829AD80E425C646DAB305381ff105169FeEcE56

[contracts]
max_number_of_chains = 100
protocol_upgrade_handler_proxy_address = "0xE30Dca3047B37dc7d88849dE4A4Dc07937ad5Ab3"
create2_factory_salt = "0x74f3fd277e2832d70f0589b8840aa5b3af5e02b85600a6978587f95813e646ae"
validator_timelock_execution_delay = 10800
genesis_root = "0x7bdb3d822ad837a3611c436d3be457363a08d06d83b74469831482353a7d8277"
genesis_rollup_leaf_index = 68
genesis_batch_commitment = "0x81f5e324a4019e4161fb9dc5058a588aa364a551fdd5c0e8788521e64e7ad596"
recursion_node_level_vk_hash = "0x0000000000000000000000000000000000000000000000000000000000000000"
recursion_leaf_level_vk_hash = "0x0000000000000000000000000000000000000000000000000000000000000000"
recursion_circuits_set_vks_hash = "0x0000000000000000000000000000000000000000000000000000000000000000"
priority_tx_max_gas_limit = 72000000
diamond_init_pubdata_pricing_mode = 0
diamond_init_batch_overhead_l1_gas = 1000000
diamond_init_max_pubdata_per_batch = 120000
diamond_init_max_l2_gas_per_batch = 80000000
diamond_init_priority_tx_max_pubdata = 99000
diamond_init_minimal_l2_gas_price = 250000000
bootloader_hash = "0x0100088580465d88420e6369230ee94a32ff356dbcdd407a4be49fc8009b2a81"
default_aa_hash = "0x010004dbf8be36c421254d005352f8245146906919be0099e8a50d0e78df85e0"
bridgehub_proxy_address = "0x303a465B659cBB0ab36eE643eA362c509EEb5213"
transparent_proxy_admin = "0xC2a36181fB524a6bEfE639aFEd37A67e77d62cf1"

[tokens]
token_weth_address = "0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2"
