era_chain_id = 270

[contracts]
bridgehub_proxy_address = "0xC0F09Cb637DCfDe54D8B7b5170736Ec21aBB33cd"
rollup_da_manager = "0xeb7c0daaddfb52afa05400b489e7497b271d6122"
l1_bytecodes_supplier_addr = "0x662B8fE285BB3aab483e75Ec46136e01aaa154f9"
ctm_proxy_address = "0x7f5401a0a0340f6a68fe3162e7bb3a57e262d18e"

