era_chain_id = 270

# This should always be false for non-loadtest environments.
support_l2_legacy_shared_bridge_test = false

priority_txs_l2_gas_limit = 2000000
max_expected_l1_gas_price = 50000000000

[contracts]
create2_factory_salt = "0x83de3677ffea74c9815331db7f4c737a32c161db4cae7d47504a336c4c5bcfb7"
create2_factory_addr = "0x4e59b44847b379578588920cA78FbF26c0B4956C"
bridgehub_proxy_address = "0xC0F09Cb637DCfDe54D8B7b5170736Ec21aBB33cd"
rollup_da_manager = "0xeb7c0daaddfb52afa05400b489e7497b271d6122"
l1_bytecodes_supplier_addr = "0x662B8fE285BB3aab483e75Ec46136e01aaa154f9"
ctm_proxy_address = "0x7f5401a0a0340f6a68fe3162e7bb3a57e262d18e"

[gateway]
chain_id = 123

[gateway.gateway_state_transition]
chain_type_manager_proxy_addr = "0x7f5401a0a0340f6a68fe3162e7bb3a57e262d18e"
chain_type_manager_proxy_admin = "0x0f7bef9694575a0e149dad6808d69f678746608b"
rollup_da_manager = "0x064ac968CCad1948fceE025fD59c20b153c88072"
rollup_sl_da_validator = "0x719A5aE8dF7468C7E1C22278eD3fD472e9904604"