era_chain_id = 324
testnet_verifier = false
governance_upgrade_timer_initial_delay = 1058400

owner_address = "0x0000000000000000000000000000000000000000"
# This should always be false for non-loadtest environments.
support_l2_legacy_shared_bridge_test = false

refund_recipient = "0x85EDD4c9eC14B17Ed1c4442cfb8C2D8d64285FC4"
# The one from v27 upgrade
rollup_l2_da_validator = "0x64E2AfcFE648201b2F4a749aF0B7229ecfa44281"
# The one from v26 upgrade
old_rollup_l2_da_validator = "0xfa96A3Da88f201433911bEFf3Ecc434CB1222731"

gateway_chain_id=9075

# The same as in v27
force_deployments_data = "0x000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000001440000000000000000000000008829ad80e425c646dab305381ff105169feece56010000fbbf5e37826b71bed7ec92a530feed3441e2f20fe085eaaf709c1ac872000000000000000000000000f41eca3047b37dc7d88849de4a4dc07937ad6bc40000000000000000000000000000000000000000000000000000000000000064010009ad0031a6e4faf066d2272679185ff89b582837af687aaa84ae8d515b8c010004cf4b79057c7de304b2cdc8ab2b4e1e33c9f345e9f5c560a12b4b1aa64b010007ed389525b956c17da38dcc6d7dd8a8ef40beef423584d8639a5d3be48a01000323e344639b41c95c459d78889fbd367c05f05fcc9cb8e2bf5bb4f685ba000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"

[contracts]
# Not used in this upgrade
governance_min_delay = 0

max_number_of_chains = 100

create2_factory_salt = "0xbe55d7b636cd46e3c4a74eb19d3a6218455bddfc0f5787f00c6286d02197fb17"
create2_factory_addr = "0x4e59b44847b379578588920cA78FbF26c0B4956C"
validator_timelock_execution_delay = 0 # Not used in this upgrade

# All the genesis / chain params should be identical to v27
genesis_root = "0xb192c5937e91363c0b880faf0568b0621a3b16010cb2df42b588972516c1d4fe"
genesis_rollup_leaf_index = 76
genesis_batch_commitment = "0xe23f2436b09ef15ba64ec3f30dc26833dda86d6dd6bef7ba6f8274e434801d05"
recursion_node_level_vk_hash = "0x0000000000000000000000000000000000000000000000000000000000000000"
recursion_leaf_level_vk_hash = "0x0000000000000000000000000000000000000000000000000000000000000000"
recursion_circuits_set_vks_hash = "0x0000000000000000000000000000000000000000000000000000000000000000"
priority_tx_max_gas_limit = 72000000
diamond_init_pubdata_pricing_mode = 0
diamond_init_batch_overhead_l1_gas = 1000000
diamond_init_max_pubdata_per_batch = 120000
diamond_init_max_l2_gas_per_batch = 80000000
diamond_init_priority_tx_max_pubdata = 99000
diamond_init_minimal_l2_gas_price = 250000000
bootloader_hash = "0x0100087fe7df1cf5616646f85bd5eebc8efe5d8deac4d85bea9b9aefd88803dd"
default_aa_hash = "0x0100050bf9baf9d08e5d3c037f8d8b486076de7e6dceb3f3fc0989ea2c99cd67"
evm_emulator_hash = "0x01000bbb8116fe7bdf690c19740ea350375426cec23f4f1f69a12fdc58adc9ba"
bridgehub_proxy_address = "0x35A54c8C757806eB6820629bc82d90E056394C92"
transparent_proxy_admin = "0x0358BACa94dcD7931B7BA7aAf8a5Ac6090E143a5"
rollup_da_manager = "0xE689e79a06D3D09f99C21E534cCF6a8b7C9b3C45"

governance_security_council_address = "0xBDFfCC71FE84020238F2990a6D2954e87355De0D"
latest_protocol_version = 0x1b00000000
l1_bytecodes_supplier_addr = "0xC9F20FC268Fc3e0e597660550033Bf2C24218fd8"
protocol_upgrade_handler_proxy_address = "0xE30Dca3047B37dc7d88849dE4A4Dc07937ad5Ab3"
protocol_upgrade_handler_impl_address = "0x0A67f0Fd2f7523057039F14969Fe23a5f620f19A"

[tokens]
token_weth_address = "0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2"
