
old_protocol_version = 0x1d00000000
bridgehub_proxy_address = "0xC0F09Cb637DCfDe54D8B7b5170736Ec21aBB33ce"

[chain]
chain_id = 270

[contracts]

genesis_root = "0x934d46a331e4c617767cade322bc4d262899c0dc5568d2019d4e11301c0cc032"
genesis_rollup_leaf_index = 84
genesis_batch_commitment = "0x4df2f475a7b24cf76a9bafca7b39a081028537c6f01993ceb5cf394eda16cca1"
recursion_node_level_vk_hash = "0x0000000000000000000000000000000000000000000000000000000000000000"
recursion_leaf_level_vk_hash = "0x0000000000000000000000000000000000000000000000000000000000000000"
recursion_circuits_set_vks_hash = "0x0000000000000000000000000000000000000000000000000000000000000000"
bootloader_hash = "0x01000911c4db4fe62c98e180cfa7e9b3a22fb15f505905d4bf36192f481551e6"
default_aa_hash = "0x010005f73e7c299ed73db937843643bdc276cbc2cc8596287e1e0cf3afc60252"
evm_emulator_hash = "0x01000d8bae37b82f311186426184866498b357f41d7a02ced11f3e3fbfbacd63"
latest_protocol_version = 0x1d00000002
new_protocol_version = 0x1d00000002
