era_chain_id = 531050204
testnet_verifier = true
governance_upgrade_timer_initial_delay = 1200
owner_address = "0xe3a615778aeEC76df1B368948a1D1614497Db858"

# This should always be false for non-loadtest environments.
support_l2_legacy_shared_bridge_test = false

old_protocol_version = "0x1d00000001"

priority_txs_l2_gas_limit = 2000000
max_expected_l1_gas_price = 50000000000
is_zk_sync_os = true

[contracts]
governance_min_delay = 0

max_number_of_chains = 100
create2_factory_salt = "0x55de3677ffea74c9815331db7f4c737a32c161db4cae7d47504a336c4c5bcfb5"
create2_factory_addr = "0x4e59b44847b379578588920cA78FbF26c0B4956C"
validator_timelock_execution_delay = 0
genesis_root = "0x6ef70107782e23150da78ff573ce332747a988e77518739723924e4f5593be22"
genesis_rollup_leaf_index = 0
genesis_batch_commitment = "0000000000000000000000000000000000000000000000000000000000000001"
recursion_node_level_vk_hash = "0x0000000000000000000000000000000000000000000000000000000000000000"
recursion_leaf_level_vk_hash = "0x0000000000000000000000000000000000000000000000000000000000000000"
recursion_circuits_set_vks_hash = "0x0000000000000000000000000000000000000000000000000000000000000000"
priority_tx_max_gas_limit = 72000000
diamond_init_pubdata_pricing_mode = 0
diamond_init_batch_overhead_l1_gas = 1000000
diamond_init_max_pubdata_per_batch = 120000
diamond_init_max_l2_gas_per_batch = 80000000
diamond_init_priority_tx_max_pubdata = 99000
diamond_init_minimal_l2_gas_price = 250000000
bootloader_hash = "0x0000000000000000000000000000000000000000000000000000000000000001"
default_aa_hash = "0x0000000000000000000000000000000000000000000000000000000000000001"
evm_emulator_hash = "0x0000000000000000000000000000000000000000000000000000000000000001"
bridgehub_proxy_address = "0xc4fd2580c3487bba18d63f50301020132342fdbd"
rollup_da_manager = "0xB168490e38E5E7e1B8eB256a701Ee8314Cbf0E15"

governance_security_council_address = "0x25Ab0397DA109A50C8921A1d4a034e0973602469"
latest_protocol_version = "0x1e00000000"
l1_bytecodes_supplier_addr = "0x3ad11E8BAAa24708086EEdaEE28722B8c1489e3b"
protocol_upgrade_handler_proxy_address = "0xe3a615778aeEC76df1B368948a1D1614497Db858"

[tokens]
token_weth_address = "0x7b79995e5f793a07bc00c21412e50ecae098e7f9"


# Note, that we actually dont contain the gateway on this env, but we need
# for the script. We reuse era chain id.
[gateway]
chain_id = 531050204

[zksync_os]
state_transition_manager = "0x54D55e74De9c6003E7a68a1fE70E633f05761eb5"
sample_chain_id = 531050204

[state_transition]
admin_facet_addr = "0x493EE7a0AbB24C0550BB57243ff3Fe93D169842B"
default_upgrade_addr = "0xDA65afc634528bC2ef5149d811Acda864dD78Ab6"
diamond_init_addr = "0x84B53B9F74921112681461275ac26363bF396D77"
executor_facet_addr = "0x130a4150562aA510b79292100A9Af0C90244e085"
genesis_upgrade_addr = "0x7Dde6ce8Ee4865f4BBD134d3BE827DBE5282100E"
getters_facet_addr = "0xae5cbB5f70e134668a13d7C8EcEF5e9E6FffCF22"
verifier_addr = "0x953d58723b3D643880d4951Ec540fc011d4D459b"

[gateway.gateway_state_transition]
chain_type_manager_proxy_addr = "0x018389676b80E677C9FAc34d04408A1F8489Bd66"
rollup_da_manager = "0x5bbEbcB4f6fa0b6E05902402ED080FB4C44EC5D3"
chain_type_manager_proxy_admin = "0x9f52db4aea9277517c6779d65f90fe03d7533730"
rollup_sl_da_validator = "0x931661BAdBc221bd686446F17A0EA40aa5196779"
admin_facet_addr = "0x108AdFfDDB323C56a64822fD186Ca4f86cC150E1"
default_upgrade_addr = "0x69653a812038424290EFd0e7Ae8DcFB2Bbf9c9b2"
diamond_init_addr = "0x0ba2a65bb5CaB6b4b4CA797C4Aa825118a6A2A63"
executor_facet_addr = "0x662B6f997F7d5AB22159cDF1B47A73199f911dbD"
genesis_upgrade_addr = "0x540E6ED9FC06dFCbf0a38Dcc7Ed7Ea3F56C551de"
getters_facet_addr = "0xEE7f08400FDa3A46D32Ae78eBEC2D3841CeC53b7"
verifier_addr = "0x9Cc4A8412Df560F2E77E3D85e14b7727d88cb043"
