era_chain_id = 13377331
testnet_verifier = true
governance_upgrade_timer_initial_delay = 120

[contracts]
max_number_of_chains = 100
create2_factory_salt = "0x0000000000000000000000000000000000000000000000000000000000000000"
validator_timelock_execution_delay = 0
genesis_root = "0xf9030b78c5bf5ac997a76962aa32c90a6d8e8ebce9838c8eeb388d73e1f7659a"
genesis_rollup_leaf_index = 64
genesis_batch_commitment = "0x34c1b220363e0cde7eaf10fe95754d61de097e0f9d9a1dc56c8026562e395259"
recursion_node_level_vk_hash = "0x0000000000000000000000000000000000000000000000000000000000000000"
recursion_leaf_level_vk_hash = "0x0000000000000000000000000000000000000000000000000000000000000000"
recursion_circuits_set_vks_hash = "0x0000000000000000000000000000000000000000000000000000000000000000"
priority_tx_max_gas_limit = 72000000
diamond_init_pubdata_pricing_mode = 0
diamond_init_batch_overhead_l1_gas = 1000000
diamond_init_max_pubdata_per_batch = 120000
diamond_init_max_l2_gas_per_batch = 80000000
diamond_init_priority_tx_max_pubdata = 99000
diamond_init_minimal_l2_gas_price = 250000000
bootloader_hash = "0x010008e5b883de8897598e83d383e332b87d09164363816c15f22353c3cd910d"
default_aa_hash = "0x0100052307b3b66ef67935255483d39b3c8dcdb47fdf94dddca11ebe8271afe6"
bridgehub_proxy_address = "0xbcb012c6a973f971c987a3be4ff3a75fe9510bcb"
transparent_proxy_admin = "0x8b7e5ca7dd323657a1a276ef5aa3ab6454c90c53"

[tokens]
token_weth_address = "0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2"
