era_chain_id = 324
testnet_verifier = false
governance_upgrade_timer_initial_delay = 1058400

[contracts]
max_number_of_chains = 100
create2_factory_salt = "0xde6b9c610417de5c775c1601c947f482e4f4e30c0f7b848c6d2b0554d76f607e"
validator_timelock_execution_delay = 0
genesis_root = "0x351670c8039e0711f150ef7be78ddfd1274f9c6a015f52db2b9db4b70b5ae13e"
genesis_rollup_leaf_index = 76
genesis_batch_commitment = "0xf9a75ccb1d8c31ae644851b4cd1da1cc5fcdd91388c5cd9fe78a4d234e608fc3"
recursion_node_level_vk_hash = "0x0000000000000000000000000000000000000000000000000000000000000000"
recursion_leaf_level_vk_hash = "0x0000000000000000000000000000000000000000000000000000000000000000"
recursion_circuits_set_vks_hash = "0x0000000000000000000000000000000000000000000000000000000000000000"
priority_tx_max_gas_limit = 72000000
diamond_init_pubdata_pricing_mode = 0
diamond_init_batch_overhead_l1_gas = 1000000
diamond_init_max_pubdata_per_batch = 120000
diamond_init_max_l2_gas_per_batch = 80000000
diamond_init_priority_tx_max_pubdata = 99000
diamond_init_minimal_l2_gas_price = 250000000
bootloader_hash = "0x0100087fe7df1cf5616646f85bd5eebc8efe5d8deac4d85bea9b9aefd88803dd"
default_aa_hash = "0x0100050bf9baf9d08e5d3c037f8d8b486076de7e6dceb3f3fc0989ea2c99cd67"
evm_emulator_hash = "0x01000bbb8116fe7bdf690c19740ea350375426cec23f4f1f69a12fdc58adc9ba"
bridgehub_proxy_address = "0x303a465B659cBB0ab36eE643eA362c509EEb5213"
transparent_proxy_admin = "0xC2a36181fB524a6bEfE639aFEd37A67e77d62cf1"

[tokens]
token_weth_address = "0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2"
