era_chain_id = 271
testnet_verifier = true
governance_upgrade_timer_initial_delay = 86400

[contracts]
max_number_of_chains = 100
create2_factory_salt = "0x8c8c6108a96a14b59963a18367250dc2042dfe62da8767d72ffddb03f269ffcc"
validator_timelock_execution_delay = 0
genesis_root = "0x32e89b79ff1671fd5575431648ffb161fd5938cf1d1e714e3c01b66e6c096742"
genesis_rollup_leaf_index = 68
genesis_batch_commitment = "0x6b2fe82ff4d96cf2970c18ee51a64891f29a8cef3f08b21344e14cdf390de185"
recursion_node_level_vk_hash = "0x0000000000000000000000000000000000000000000000000000000000000000"
recursion_leaf_level_vk_hash = "0x0000000000000000000000000000000000000000000000000000000000000000"
recursion_circuits_set_vks_hash = "0x0000000000000000000000000000000000000000000000000000000000000000"
priority_tx_max_gas_limit = 72000000
diamond_init_pubdata_pricing_mode = 0
diamond_init_batch_overhead_l1_gas = 1000000
diamond_init_max_pubdata_per_batch = 120000
diamond_init_max_l2_gas_per_batch = 80000000
diamond_init_priority_tx_max_pubdata = 99000
diamond_init_minimal_l2_gas_price = 250000000
bootloader_hash = "0x0100088580465d88420e6369230ee94a32ff356dbcdd407a4be49fc8009b2a81"
default_aa_hash = "0x010004dbf8be36c421254d005352f8245146906919be0099e8a50d0e78df85e0"
bridgehub_proxy_address = "0x7bdf7970f17278a6ff75fdbc671e870b0728ae41"
transparent_proxy_admin = "0x93aeee8d98fb0873f8ff595fdd534a1f288786d2"

[tokens]
token_weth_address = "0x7b79995e5f793A07Bc00c21412e50Ecae098E7f9"