era_chain_id = 300
testnet_verifier = true
governance_upgrade_timer_initial_delay = 86400

[contracts]
max_number_of_chains = 100
governance_address = "0xe3a615778aeEC76df1B368948a1D1614497Db858"
create2_factory_salt = "0x8c8c6108a96a14b59963a18367250dc2042dfe62da8767d72ffddb03f269ffcc"
validator_timelock_execution_delay = 0
genesis_root = "0xd8c9be7efb705e7dcf529c14fce7048ea99dea9eab6a6b4e5f8de1ebf4f2ebf2"
genesis_rollup_leaf_index = 68
genesis_batch_commitment = "0xf6e873e8894b90f157511a133d941fb6f0892f83147e3d0d2cafa71af8c838e5"
recursion_node_level_vk_hash = "0x0000000000000000000000000000000000000000000000000000000000000000"
recursion_leaf_level_vk_hash = "0x0000000000000000000000000000000000000000000000000000000000000000"
recursion_circuits_set_vks_hash = "0x0000000000000000000000000000000000000000000000000000000000000000"
priority_tx_max_gas_limit = 72000000
diamond_init_pubdata_pricing_mode = 0
diamond_init_batch_overhead_l1_gas = 1000000
diamond_init_max_pubdata_per_batch = 120000
diamond_init_max_l2_gas_per_batch = 80000000
diamond_init_priority_tx_max_pubdata = 99000
diamond_init_minimal_l2_gas_price = 250000000
bootloader_hash = "0x0100088580465d88420e6369230ee94a32ff356dbcdd407a4be49fc8009b2a81"
default_aa_hash = "0x010004dbf8be36c421254d005352f8245146906919be0099e8a50d0e78df85e0"
bridgehub_proxy_address = "0x35A54c8C757806eB6820629bc82d90E056394C92"
transparent_proxy_admin = "0x0358BACa94dcD7931B7BA7aAf8a5Ac6090E143a5"

[tokens]
token_weth_address = "0x7b79995e5f793A07Bc00c21412e50Ecae098E7f9"
