era_chain_id = 324
testnet_verifier = false
# Unused
governance_upgrade_timer_initial_delay = 0
# Note, that this is NOT the owner of the bridgehub, but the owner of the zksync os CTM.
owner_address = "0xc66f0b45c05cf654eec093650fd67865e85e8566"

# This should always be false for non-loadtest environments.
support_l2_legacy_shared_bridge_test = false

old_protocol_version = "0x1e00000000"

priority_txs_l2_gas_limit = 2000000
max_expected_l1_gas_price = 30000000000
is_zk_sync_os = true
redeploy_da_manager = true

[contracts]
governance_min_delay = 0

max_number_of_chains = 100
create2_factory_salt = "0x3000000000000000000000000000000000000000000000000000001e00000001"
create2_factory_addr = "0x4e59b44847b379578588920cA78FbF26c0B4956C"
validator_timelock_execution_delay = 10800
genesis_root = "0x423c107626aff95d3d086eabd92132dc9485e021ae3cb4c7735d5e963578e3d0"
genesis_rollup_leaf_index = 0
genesis_batch_commitment = "0000000000000000000000000000000000000000000000000000000000000001"
recursion_node_level_vk_hash = "0x0000000000000000000000000000000000000000000000000000000000000000"
recursion_leaf_level_vk_hash = "0x0000000000000000000000000000000000000000000000000000000000000000"
recursion_circuits_set_vks_hash = "0x0000000000000000000000000000000000000000000000000000000000000000"
priority_tx_max_gas_limit = 72000000
diamond_init_pubdata_pricing_mode = 0
diamond_init_batch_overhead_l1_gas = 1000000
diamond_init_max_pubdata_per_batch = 120000
diamond_init_max_l2_gas_per_batch = 80000000
diamond_init_priority_tx_max_pubdata = 99000
diamond_init_minimal_l2_gas_price = 250000000
bootloader_hash = "0x0000000000000000000000000000000000000000000000000000000000000001"
default_aa_hash = "0x0000000000000000000000000000000000000000000000000000000000000001"
evm_emulator_hash = "0x0000000000000000000000000000000000000000000000000000000000000001"
bridgehub_proxy_address = "0x303a465B659cBB0ab36eE643eA362c509EEb5213"
# Does not matter, a new one should be deployed
rollup_da_manager = "0xE689e79a06D3D09f99C21E534cCF6a8b7C9b3C45"

# Does not matter
governance_security_council_address = "0xed04b1ac422251851a3EC953Ff4395e5c2443647"

latest_protocol_version = 0x1e00000001

# Unused as bytecode supplier is not supported in this upgrade.
l1_bytecodes_supplier_addr = "0xC9F20FC268Fc3e0e597660550033Bf2C24218fd8"

# Unused, since the upgrade is done for the ecosystem.
protocol_upgrade_handler_proxy_address = "0xE30Dca3047B37dc7d88849dE4A4Dc07937ad5Ab3"
protocol_upgrade_handler_implementation_address = "0x36625Bd3dDB469377C6e9893712158cA3c0cC14B"

[tokens]
token_weth_address = "0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2"

[gateway]
chain_id = 9075

[state_transition]
admin_facet_addr = "0xa8AF3cfF5c286F07f148b9C5d4A7b3fC358b1A5E"
diamond_init_addr = "0x77E0EAf7220783b372eB694ceCd68d2663797A44"
executor_facet_addr = "0xd9232796Ee7AD3d8eB38BeF3a0c1eAF30De9d292"
genesis_upgrade_addr = "0x2bf9B0B72573af5471c4f035271616139392Acd8"
getters_facet_addr = "0xa433FcF5b1d6E9a74633fcd2391D71B49B20F4F3"
mailbox_facet_addr = "0x883E3226558C7e0A1A6586003975DBcc226E7274"
force_deployments_data = "0x0000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000001440000000000000000000000008829ad80e425c646dab305381ff105169feece56010000f1477ebc7355591c664c501757b31e9cd0025d565546fc0054f28a6411000000000000000000000000d7800b45c05cf654eec093650fd67865e85e9677000000000000000000000000000000000000000000000000000000000000006400000000000000000000000000000000000000000000000000000000000001e0000000000000000000000000000000000000000000000000000000000000034000000000000000000000000000000000000000000000000000000000000004a00000000000000000000000000000000000000000000000000000000000000600000000000000000000000000000000000000000000000000000000000000076000000000000000000000000000000000000000000000000000000000000008c00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000140000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000c000000000000000000000000000000000000000000000000000000000000000604cdf52a9a78024a7b5b1d31faa6de33eb6159ee71f02733c27de62106cb3d9ee00000000000000000000000000000000000000000000000000000000000030831dc8d8d6c1eb16ade1b790365a9007a3ca7247ee7de00b576b43e21d28918f9d0000000000000000000000000000000000000000000000000000000000000060b09a95cb43a3f5d388e945b68f8b8a814681d60e8252ed08cba7a3d591a152df0000000000000000000000000000000000000000000000000000000000000e0b09301da5bbb08e078e7a51cdb957dd25945efd0ec3b056137d344c929ecdc9c30000000000000000000000000000000000000000000000000000000000000140000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000c000000000000000000000000000000000000000000000000000000000000000601c085665f2a51715c66b88f52f86f081e01bb941faf55d5fa9dbd6fe97cd683a0000000000000000000000000000000000000000000000000000000000002c5b5ad3d9403af0d911ee4aeadbbde9c353814fdbc7679c20c99f5f944c43f1dee00000000000000000000000000000000000000000000000000000000000000060b09a95cb43a3f5d388e945b68f8b8a814681d60e8252ed08cba7a3d591a152df0000000000000000000000000000000000000000000000000000000000000e0b09301da5bbb08e078e7a51cdb957dd25945efd0ec3b056137d344c929ecdc9c30000000000000000000000000000000000000000000000000000000000000140000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000c000000000000000000000000000000000000000000000000000000000000000606dac35ffb85d51f76e2de0febb2b0f92ee424e38d51f8401773c17687a595d1c0000000000000000000000000000000000000000000000000000000000004580346683d96f68106a10b9f36edea22e1189e45255e05dd465c6d101ea2a360ab90000000000000000000000000000000000000000000000000000000000000060b09a95cb43a3f5d388e945b68f8b8a814681d60e8252ed08cba7a3d591a152df0000000000000000000000000000000000000000000000000000000000000e0b09301da5bbb08e078e7a51cdb957dd25945efd0ec3b056137d344c929ecdc9c30000000000000000000000000000000000000000000000000000000000000140000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000c000000000000000000000000000000000000000000000000000000000000000609df14aba83ab80ad0df8cd4146b743788f4fcf00d4c8e636040081d44497e639000000000000000000000000000000000000000000000000000000000000183d5865ccbc7d551fc1802e091886ffa94586436778d22ce646d4bcb392360df5c00000000000000000000000000000000000000000000000000000000000000060b09a95cb43a3f5d388e945b68f8b8a814681d60e8252ed08cba7a3d591a152df0000000000000000000000000000000000000000000000000000000000000e0b09301da5bbb08e078e7a51cdb957dd25945efd0ec3b056137d344c929ecdc9c30000000000000000000000000000000000000000000000000000000000000140000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000c000000000000000000000000000000000000000000000000000000000000000601a36318670b6ab973e68178a10d6107227fde6d027573d7668e61760d22a867a00000000000000000000000000000000000000000000000000000000000020064d5c32f28646ef26d746e078bd9d9c5797178e9959013bc13ec4ed42122d60220000000000000000000000000000000000000000000000000000000000000060b09a95cb43a3f5d388e945b68f8b8a814681d60e8252ed08cba7a3d591a152df0000000000000000000000000000000000000000000000000000000000000e0b09301da5bbb08e078e7a51cdb957dd25945efd0ec3b056137d344c929ecdc9c30000000000000000000000000000000000000000000000000000000000000140000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000c00000000000000000000000000000000000000000000000000000000000000060c49018245ed5bebb0e9124546c1716a564864c451ec6e65931cc80bbe5400cc60000000000000000000000000000000000000000000000000000000000003a13db0d981bf1867108c27f2c52334c4f31d8bb88e17f6955ce85930568086974600000000000000000000000000000000000000000000000000000000000000060b09a95cb43a3f5d388e945b68f8b8a814681d60e8252ed08cba7a3d591a152df0000000000000000000000000000000000000000000000000000000000000e0b09301da5bbb08e078e7a51cdb957dd25945efd0ec3b056137d344c929ecdc9c3"

# On mainnet there are no existing zksync os chain, thus no operations that use it are available.
# I.e. chains will not be able to upgrade from v29.1, but it is okay, since there
# are no such chains in the first place. 
[zksync_os]
sample_chain_id = 30715
# Unlike stage or testnet, there is no sample chain to get the CTM from, so 
# we have to provide it explicitly.
optional_ctm_address = "0x1adf137f59949c9081157d5de1e002d1c992071f"
current_dual_verifier = "0x5B4b58a5e65a0C4A054E0f4B67277a1bc6425bD2"

[gateway.gateway_state_transition]
chain_type_manager_proxy_addr = "0x912B84EEEEBeca74d307b9a2b09c68332aa5426C"
rollup_da_manager = "0x5E12D7E0bB68029afbeC83ccB9E8eDE6019ef073"
chain_type_manager_proxy_admin = "0x0A8a176B6F5962122C6E8F8815278f873D74021f"
rollup_sl_da_validator = "0x595b8C88B9e5f3a4c596C3e81BE6e11D53Bb9200"
