era_chain_id = 270
testnet_verifier = true
governance_upgrade_timer_initial_delay = 1200
# Note, that this is NOT the owner of the bridgehub, but the owner of the zksync os CTM.
owner_address = "0xc66f0b45c05cf654eec093650fd67865e85e8566"

# This should always be false for non-loadtest environments.
support_l2_legacy_shared_bridge_test = false

old_protocol_version = "0x1e00000000"

priority_txs_l2_gas_limit = 2000000
max_expected_l1_gas_price = 50000000000
is_zk_sync_os = true
redeploy_da_manager = false

[contracts]
governance_min_delay = 0

max_number_of_chains = 100
create2_factory_salt = "0x2000000000000000000000000000000000000000000000000000001e00000001"
create2_factory_addr = "0x4e59b44847b379578588920cA78FbF26c0B4956C"
validator_timelock_execution_delay = 0
genesis_root = "0x423c107626aff95d3d086eabd92132dc9485e021ae3cb4c7735d5e963578e3d0"
genesis_rollup_leaf_index = 0
genesis_batch_commitment = "0000000000000000000000000000000000000000000000000000000000000001"
recursion_node_level_vk_hash = "0x0000000000000000000000000000000000000000000000000000000000000000"
recursion_leaf_level_vk_hash = "0x0000000000000000000000000000000000000000000000000000000000000000"
recursion_circuits_set_vks_hash = "0x0000000000000000000000000000000000000000000000000000000000000000"
priority_tx_max_gas_limit = 72000000
diamond_init_pubdata_pricing_mode = 0
diamond_init_batch_overhead_l1_gas = 1000000
diamond_init_max_pubdata_per_batch = 120000
diamond_init_max_l2_gas_per_batch = 80000000
diamond_init_priority_tx_max_pubdata = 99000
diamond_init_minimal_l2_gas_price = 250000000
bootloader_hash = "0x0000000000000000000000000000000000000000000000000000000000000001"
default_aa_hash = "0x0000000000000000000000000000000000000000000000000000000000000001"
evm_emulator_hash = "0x0000000000000000000000000000000000000000000000000000000000000001"
bridgehub_proxy_address = "0x236D1c3Ff32Bd0Ca26b72Af287E895627c0478cE"
rollup_da_manager = "0xeb7c0daaddfb52afa05400b489e7497b271d6122"

# Does not matter
governance_security_council_address = "0xed04b1ac422251851a3EC953Ff4395e5c2443647"

latest_protocol_version = 0x1e00000001
# Unused as bytecode supplier is not supported in this upgrade.
l1_bytecodes_supplier_addr = "0x662B8fE285BB3aab483e75Ec46136e01aaa154f9"

[tokens]
token_weth_address = "0x7b79995e5f793a07bc00c21412e50ecae098e7f9"

# Note, that we actually dont contain the gateway on this env, but we need
# for the script. We reuse era chain id.
[gateway]
chain_id = 123

[zksync_os]
sample_chain_id = 2702

[state_transition]
admin_facet_addr = "0x3aD10d7B8B0E12aa9E5784C4101667B792c0bb27"
getters_facet_addr = "0x99E00FeCc2a83AfFc2614c5816451F0E2e6C969B"
mailbox_facet_addr = "0x5086f3ED0b425DF0bedf64dEe4472E35c3FFBeA2"
executor_facet_addr = "0x777eEEEfcBc804604C852cdc9db485d96A9b6F2e"
diamond_init_addr = "0xc10e1baA5DCE84435BCcE73496454c3eb790b795"
genesis_upgrade_addr = "0x6b9Eb97d2dC791977bbB952D4e9933785c3aAAd0"
verifier_addr = "0xBe953765e45FE69A6Fb9Abcc263c6Ed564e6B0b9"
force_deployments_data = "0x00000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000aa36a7000000000000000000000000000000000000000000000000000000000000010e000000000000000000000000fd3130ea0e8b7dd61ac3663328a66d97eb02f84b010000f1477ebc7355591c664c501757b31e9cd0025d565546fc0054f28a6411000000000000000000000000d7800b45c05cf654eec093650fd67865e85e9677000000000000000000000000000000000000000000000000000000000000006400000000000000000000000000000000000000000000000000000000000001e0000000000000000000000000000000000000000000000000000000000000034000000000000000000000000000000000000000000000000000000000000004a00000000000000000000000000000000000000000000000000000000000000600000000000000000000000000000000000000000000000000000000000000076000000000000000000000000000000000000000000000000000000000000008c00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000140000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000c000000000000000000000000000000000000000000000000000000000000000604cdf52a9a78024a7b5b1d31faa6de33eb6159ee71f02733c27de62106cb3d9ee00000000000000000000000000000000000000000000000000000000000030831dc8d8d6c1eb16ade1b790365a9007a3ca7247ee7de00b576b43e21d28918f9d0000000000000000000000000000000000000000000000000000000000000060b09a95cb43a3f5d388e945b68f8b8a814681d60e8252ed08cba7a3d591a152df0000000000000000000000000000000000000000000000000000000000000e0b09301da5bbb08e078e7a51cdb957dd25945efd0ec3b056137d344c929ecdc9c30000000000000000000000000000000000000000000000000000000000000140000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000c000000000000000000000000000000000000000000000000000000000000000601c085665f2a51715c66b88f52f86f081e01bb941faf55d5fa9dbd6fe97cd683a0000000000000000000000000000000000000000000000000000000000002c5b5ad3d9403af0d911ee4aeadbbde9c353814fdbc7679c20c99f5f944c43f1dee00000000000000000000000000000000000000000000000000000000000000060b09a95cb43a3f5d388e945b68f8b8a814681d60e8252ed08cba7a3d591a152df0000000000000000000000000000000000000000000000000000000000000e0b09301da5bbb08e078e7a51cdb957dd25945efd0ec3b056137d344c929ecdc9c30000000000000000000000000000000000000000000000000000000000000140000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000c000000000000000000000000000000000000000000000000000000000000000606dac35ffb85d51f76e2de0febb2b0f92ee424e38d51f8401773c17687a595d1c0000000000000000000000000000000000000000000000000000000000004580346683d96f68106a10b9f36edea22e1189e45255e05dd465c6d101ea2a360ab90000000000000000000000000000000000000000000000000000000000000060b09a95cb43a3f5d388e945b68f8b8a814681d60e8252ed08cba7a3d591a152df0000000000000000000000000000000000000000000000000000000000000e0b09301da5bbb08e078e7a51cdb957dd25945efd0ec3b056137d344c929ecdc9c30000000000000000000000000000000000000000000000000000000000000140000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000c000000000000000000000000000000000000000000000000000000000000000609df14aba83ab80ad0df8cd4146b743788f4fcf00d4c8e636040081d44497e639000000000000000000000000000000000000000000000000000000000000183d5865ccbc7d551fc1802e091886ffa94586436778d22ce646d4bcb392360df5c00000000000000000000000000000000000000000000000000000000000000060b09a95cb43a3f5d388e945b68f8b8a814681d60e8252ed08cba7a3d591a152df0000000000000000000000000000000000000000000000000000000000000e0b09301da5bbb08e078e7a51cdb957dd25945efd0ec3b056137d344c929ecdc9c30000000000000000000000000000000000000000000000000000000000000140000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000c000000000000000000000000000000000000000000000000000000000000000601a36318670b6ab973e68178a10d6107227fde6d027573d7668e61760d22a867a00000000000000000000000000000000000000000000000000000000000020064d5c32f28646ef26d746e078bd9d9c5797178e9959013bc13ec4ed42122d60220000000000000000000000000000000000000000000000000000000000000060b09a95cb43a3f5d388e945b68f8b8a814681d60e8252ed08cba7a3d591a152df0000000000000000000000000000000000000000000000000000000000000e0b09301da5bbb08e078e7a51cdb957dd25945efd0ec3b056137d344c929ecdc9c30000000000000000000000000000000000000000000000000000000000000140000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000c00000000000000000000000000000000000000000000000000000000000000060c49018245ed5bebb0e9124546c1716a564864c451ec6e65931cc80bbe5400cc60000000000000000000000000000000000000000000000000000000000003a13db0d981bf1867108c27f2c52334c4f31d8bb88e17f6955ce85930568086974600000000000000000000000000000000000000000000000000000000000000060b09a95cb43a3f5d388e945b68f8b8a814681d60e8252ed08cba7a3d591a152df0000000000000000000000000000000000000000000000000000000000000e0b09301da5bbb08e078e7a51cdb957dd25945efd0ec3b056137d344c929ecdc9c3"

[gateway.gateway_state_transition]
chain_type_manager_proxy_addr = "0x018389676b80E677C9FAc34d04408A1F8489Bd66"
rollup_da_manager = "0x5bbEbcB4f6fa0b6E05902402ED080FB4C44EC5D3"
chain_type_manager_proxy_admin = "0x9f52db4aea9277517c6779d65f90fe03d7533730"
rollup_sl_da_validator = "0x931661BAdBc221bd686446F17A0EA40aa5196779"
admin_facet_addr = "0x108AdFfDDB323C56a64822fD186Ca4f86cC150E1"
default_upgrade_addr = "0x69653a812038424290EFd0e7Ae8DcFB2Bbf9c9b2"
diamond_init_addr = "0x0ba2a65bb5CaB6b4b4CA797C4Aa825118a6A2A63"
executor_facet_addr = "0x662B6f997F7d5AB22159cDF1B47A73199f911dbD"
genesis_upgrade_addr = "0x540E6ED9FC06dFCbf0a38Dcc7Ed7Ea3F56C551de"
getters_facet_addr = "0xEE7f08400FDa3A46D32Ae78eBEC2D3841CeC53b7"
verifier_addr = "0x9Cc4A8412Df560F2E77E3D85e14b7727d88cb043"
