[package]
name = "zksync_verifier_contract_generator"
version = "0.1.0"
edition = "2021"

[dependencies]
serde_derive = "1.0"
serde_json = "1.0"
lazy_static = "1.4"
structopt = "0.3.26"
handlebars = "4.4.0"

[workspace]
