era_chain_id = 9
owner_address = "0x70997970C51812dc3A010C7d01b50e0d17dc79C8"
testnet_verifier = true
support_l2_legacy_shared_bridge_test = false
is_zk_sync_os = false

[gateway]
chain_id = 123

[contracts]
create2_factory_salt = "0x00000000000000000000000000000000000000000000000000000000000000ff"
create2_factory_addr = "0x0000000000000000000000000000000000000000"
governance_security_council_address = "0x0000000000000000000000000000000000000000"
governance_min_delay = 0
validator_timelock_execution_delay = 0
genesis_root = "0x1000000000000000000000000000000000000000000000000000000000000000"
genesis_rollup_leaf_index = 1
genesis_batch_commitment = "0x1000000000000000000000000000000000000000000000000000000000000000"
latest_protocol_version = 0
bootloader_hash = "0x0100000000000000000000000000000000000000000000000000000000000000"
default_aa_hash = "0x0100000000000000000000000000000000000000000000000000000000000000"
evm_emulator_hash = "0x0100000000000000000000000000000000000000000000000000000000000000"
